// Generated by CoffeeScript 1.3.3
(function() {
  var assert, helper;

  helper = require('../index').Helper;

  assert = require('assert');

  module.exports = {
    'test strip': function() {
      assert.equal("abc", helper.strip(" abc"));
      assert.equal("abc", helper.strip("abc "));
      return assert.equal("abc", helper.strip("  abc  "));
    },
    'test gsub': function() {
      assert.equal("abcabc", helper.gsub("-abc-abc-", /[^a-z0-9 ]/i, ''));
      assert.equal("*abc*abc*", helper.gsub("-abc-abc-", /[^a-z0-9 ]/i, '*'));
      return assert.equal("abcabc", helper.gsub("!@#abc-!@#abc!@#", /[^a-z0-9 ]/i, ''));
    },
    'test gsub with errors': function() {
      assert.equal("-abc-abc-", helper.gsub("-abc-abc-"));
      return assert.equal("-abc-abc-", helper.gsub("-abc-abc-", /(?:)/));
    },
    'test normalize': function() {
      assert.equal("abc", helper.normalize("a-bc"));
      assert.equal("a bc", helper.normalize("a bc"));
      return assert.equal("ab!@#s%^&*()c", helper.normalize("a-b!@#$%^&*()c"));
    }
  };

}).call(this);
